### ISSUE TITLE
autorecover parallel service calls

### ISSUE THREAD

**Issue by benmaidel** [4am-robotics/cob_command_tools#224]
autorecover waits for the recover service on every component. If one component is not available the others will never be recovered/initialized.
Just call the services via sss with the blocking=false param and collect the handle's. When every component is recovered, check all collected handel's for success.

@fmessmer FYI

**Comment by fmessmer** [comment]
I started an implementation in #225 

however, the handle-based approach is not possible without re-writing the script_server because in the `blockin=false` case the service call is executed in a thread and the service result is never passed back to the handle
thus, for `auto_recover` the error code will always stay `-1`...

**Comment by fmessmer** [comment]
solved by having component-specific `auto_init` and `auto_recover` nodes
