### ISSUE TITLE
use service_ns instead of full_service_name in sss for mimic

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_command_tools#90]
in sss we use the full service name for mimic. we should move mimic into a standalone namespace and the use this as service_ns

maybe needs modifications in cob_mimic and cob_bringup.

**Comment by fmessmer** [comment]
Make sure these two blocks are consistant:
[set_mimic](https://github.com/ipa320/cob_command_tools/blob/indigo_dev/cob_script_server/src/simple_script_server/simple_script_server.py#L816-L821)
[set_light](https://github.com/ipa320/cob_command_tools/blob/indigo_dev/cob_script_server/src/simple_script_server/simple_script_server.py#L730-735)

Maybe we can change both cob_light and cob_mimic to advertise services set_light and set_mimic respectively (instead of using mode for cob_light and set_mimic for cob_mimic)

**Comment by fmessmer** [comment]
this could also be something for the Wednesday-Hackathon...

**Comment by fmessmer** [comment]
done!
